# From: https://about.gitlab.com/2017/09/21/how-to-create-ci-cd-pipeline-with-autodeploy-to-kubernetes-using-gitlab-and-helm/

cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
    - vendor/

variables:
  REPO_DIR: gitlab.com/elixxir
  REPO_NAME: gpumathsnative
  DOCKER_IMAGE: elixxirlabs/cuda-go:latest

before_script:
  - echo $CI_BUILD_REF
  - echo $CI_PROJECT_DIR
  - echo $PWD
  - echo $USER
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan -t rsa gitlab.com > ~/.ssh/known_hosts
  - git config --global url."git@$GITLAB_SERVER:elixxir/".insteadOf "https://gitlab.com/elixxir/"
  - git config --global url."git@$GITLAB_SERVER:xx_network/".insteadOf "https://gitlab.com/xx_network/" --add
  - git config --global url."git@$GITLAB_SERVER:elixxir/".insteadOf "https://git.xx.network/elixxir/" --add
  - git config --global url."git@$GITLAB_SERVER:xx_network/".insteadOf "https://git.xx.network/xx_network/" --add

stages:
  - setup
  - trigger_server
  - trigger_release_server

setup:
  stage: setup
  image: $DOCKER_IMAGE
  except:
    - tags
  script:
    - cd cgbnBindings/powm
    - make turing
    - make devinstall
  artifacts:
    paths:
     - lib/

# TODO(?): have server pull in the latest from release/master automatically for this pipeline, if possible
trigger_server:
  stage: trigger_server
  script:
    - "curl -X POST -F token=5be79349e632bcd07f452d04cc0583 -F ref=master https://gitlab.com/api/v4/projects/5014439/trigger/pipeline"
  only:
    - master

trigger_release_server:
  stage: trigger_release_server
  script:
    - "curl -X POST -F token=5be79349e632bcd07f452d04cc0583 -F ref=release https://gitlab.com/api/v4/projects/5014439/trigger/pipeline"
  only:
    - release
